### PR TITLE
Rename `metadata.json` to `{contract_name}.json`

### LINKED ISSUE #950: Rename `metadata.json` to `{contract_name}.json`
I don't think it makes sense to name the `contract` and `wasm` file after the contract but not the metadata file. It is just annoying to not be able to see from the file name which contract it belongs to.

### PR DESCRIPTION
**Pull request by SkymanOne**
Closes #950

### CODE REVIEW

**Review by cmichi — COMMENTED** [review]
Changelog entry plz.

**Comment by kvinwang** [comment]
Oh, this is a breaking change. We have tools reading the contract name from the `metadata.json`.

**Comment by ascjones** [comment]
@kvinwang makes a good point. We should think carefully before introducing breaking changes.

https://github.com/paritytech/cargo-contract/issues/950#issuecomment-1418951627

**Comment by ascjones** [comment]
On balance, I think this is reasonable to introduce as a breaking change into the `2.0.0` release. https://github.com/paritytech/cargo-contract/issues/950#issuecomment-1420657886

The main thing is for consistency with other artefact file names.

Downstream tools which depend on the static name will instead have to handle any `*.json` file as a contract metadata file. A breaking change, yes, but relatively easy to fix.

**Review by ascjones — APPROVED** [review]

**Review by athei — APPROVED** [review]

**Comment by ascjones** [comment]
> here should be no guarantee that there is only one *.json file in the target/ink directory, and it is a metadata file.

The guarantee now is that the `ink/mycontract.wasm` artifact always exists, and unless it was built with `--build-artifacts code-only`, there will exist `mycontract.json` (metadata only) and `mycontract.contract` (metadata + code).

**Comment by ascjones** [comment]
The way to determine the contract name is to take the first part of the `.wasm` code artefact. So `erc20.wasm` -> `erc20.json`. No matter if there is a `foo.json` alongside or not.

The edge case with this is that if you rename your contract, then there will be multiple `.wasm` files in the `ink` directory. In this case you could just choose the most recent one or look at `Cargo.toml` to determine the package name.

> Cargo.toml in which the contract name isn't well-defined either and it isn't script friendly and isn't always available

We have recently changed it so the contract name is always the package name https://github.com/paritytech/cargo-contract/pull/929. But anyway it should not be required in this case because of the above heuristic (all contract artifacts have the same root name, different extensions)

**Comment by kvinwang** [comment]
> The way to determine the contract name is to take the first part of the `.wasm` code artefact. So `erc20.wasm` -> `erc20.json`. No matter if there is a `foo.json` alongside or not.

I don't think this is a good design. This is like asking the tools to guess `what's my name`. A `metadata.json` definitely solves the problem in the simplest and most robust way.

**Comment by kvinwang** [comment]
> The tool doesn't need to guess what the name is, the name is now the name of the `json` file itself. The `target/ink` directory generated by `cargo-contract` only contains `json` files which are contract metadata, so that is a good enough guarantee.

Given there is `ink/` dir with guaranteed a `mycontract.contract`, a `mycontract.wasm` and a `mycontract.json` inside.
But without guarantee, there is not any `foo.json`, `bar.wasm` inside.
How can I know which file is the contract metadata file or contains the contract name? 
The first `.json` file found?

**Comment by ascjones** [comment]
> But without guarantee, there is not any foo.json, bar.wasm inside.

I'm not exactly sure what you mean here, but if you are asking how to identify the file when it is not inside `target/ink`, then there are no guarantees anymore because `cargo-contract` is only in control of artifacts in that directory. That was also true when it was called `metadata.json`, because as well as being copied it could also be renamed. So you are in full control of the name, so you can also `cp target/ink/mycontract.json metadata.json` if you wish when copying it to your assets directory.

**Comment by SkymanOne** [comment]
@kvinwang I reckon the obvious benefit of matching the metadata file with the contract's name is that sometimes you only have metadata file and meaningful name helps to understand which contract it belongs to.

We already encountered an instance of such problem: we have a workshop https://github.com/paritytech/ink-workshop where game.contract is deployed by someone else and the player had to upload metadata in polkadot.js ui to be able to read the game's contracts.

**Comment by kvinwang** [comment]
> I'm not exactly sure what you mean here, but if you are asking how to identify the file when it is not inside `target/ink`, then there are no guarantees anymore because `cargo-contract` is only in control of artifacts in that directory.

I mean there is no guarantee that `cargo-contract 2.1` or any future version never generates a `foo.json` in the `ink/` dir there. If cargo-contract generates an additional `foo.json`, it would not be considered a breaking change. But it would totally break downstream build tools.

Let me show a piece of pseudocode code here.

Suppose we have a downstream build script like this:
```bash
cargo contract build --release
CONTRACT_NAME=`jq -r .contract.name target/ink/metadata.json`
```

Now, we might need to be changed to:
```bash
cargo contract build --release
CONTRACT_NAME=`cat target/ink/*.json | jq -r .contract.name`
```

Do you think the command `cat target/ink/*.json` would be never broken by any future `cargo-contract` updates? No, obviously, `cargo-contract` can not give such a weird guarantee.

I think a better solution might be adding an option to assign the metadata file name by the caller. So the script would be like:
```bash
cargo contract build --release --metadata target/ink/metadata.json
CONTRACT_NAME=`jq -r .contract.name target/ink/metadata.json`
```

**Comment by kvinwang** [comment]
> @kvinwang I reckon the obvious benefit of matching the metadata file with the contract's name is that sometimes you only have metadata file and meaningful name helps to understand which contract it belongs to.
> 
> We already encountered an instance of such problem: we have a workshop https://github.com/paritytech/ink-workshop where game.contract is deployed by someone else and the player had to upload metadata in polkadot.js ui to be able to read the game's contracts.

Downstream tools can easily rename the `metadata.json` to `mycontract.json`, but not vice versa.

**Comment by SkymanOne** [comment]
> > @kvinwang I reckon the obvious benefit of matching the metadata file with the contract's name is that sometimes you only have metadata file and meaningful name helps to understand which contract it belongs to.
> > We already encountered an instance of such problem: we have a workshop https://github.com/paritytech/ink-workshop where game.contract is deployed by someone else and the player had to upload metadata in polkadot.js ui to be able to read the game's contracts.
> 
> Downstream tools can easily rename the `metadata.json` to `mycontract.json`, but not vice versa.
> 
> I think a better solution might be adding an option to assign the metadata file name by the caller. Like: `cargo contract build --release --metadata target/ink/metadata.json`

Why? :)

**Comment by kvinwang** [comment]
> Why? :)

I explained it in [this comment](https://github.com/paritytech/cargo-contract/pull/952#issuecomment-1421708090) above.

**Comment by ascjones** [comment]
```
cargo contract build --release
CONTRACT_NAME=`jq -r .contract.name target/ink/metadata.json`
```
To make such a script more robust and agnostic of the file path of the metadata, you can read the path of the metadata from the build result e.g.:

```
cargo contract build --output-json | jq -r .metadata_result.dest_metadata
```
image

**Comment by kvinwang** [comment]
> cargo contract build --output-json | jq -r .metadata_result.dest_metadata

Cool! Didn't know there is so much useful info in the JSON output.

**Pull request merged**
