### PR TITLE
Introduce `rusty-cachier` and remove old `pre_cache.sh`

### PR DESCRIPTION
**Pull request by rcny**
This PR enables `rusty-cachier` for this project, which will allow future PRs to reuse `CARGO_HOME` and `CARGO_TARGET_DIR` caches from the latest `master`, improving run time for all Rust-related CI jobs.

### CODE REVIEW

**Comment by rcny** [comment]
`rusty-cachier` fails gracefully now as it awaits cache population from `master` and its later distribution to the all related runner machines via the scheduler.
@TriplEight Let's proceed and merge it as is into `master`.

**Review by alvicsam — APPROVED** [review]

**Review by TriplEight — APPROVED** [review]
LGTM. Just be aware tat you're doing snapshots on every run, not just on master.

**Review by ascjones — COMMENTED** [review]
What's `rusty-cachier`? An internal tool we have developed?

**Comment by rcny** [comment]
> Just be aware tat you're doing snapshots on every run, not just on master.

`rusty-cachier snapshot create` command creates union mounts, it doesn't downloads/uploads any cache entitities.

> What's `rusty-cachier`? An internal tool we have developed?

Yes, our [new caching tool](https://gitlab.parity.io/parity/infrastructure/ci_cd/rusty-cachier/client).

**Pull request merged**
